## Importing libraries

In [ ]:
import pandas as pd
import numpy as np

## Importing Dataset

In [3]:
ds = pd.read_csv("dataset.csv",sep=";")
ds.head(5)

                                                text  emotion
0  im feeling rather rotten so im not very ambiti...  sadness
1          im updating my blog because i feel shitty  sadness
2  i never make her separate from me because i do...  sadness
3  i left with my bouquet of red and yellow tulip...      joy
4    i was feeling a little vain when i did this one  sadness

## Dataset Information

In [4]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   text     2000 non-null   object
 1   emotion  2000 non-null   object
dtypes: object(2)
memory usage: 31.4+ KB

In [5]:
ds['emotion'].value_counts()

emotion
joy         695
sadness     581
anger       275
fear        224
love        159
surprise     66
Name: count, dtype: int64

## Data Preprocessing

### Tweets usually contain:

- URLs
- special characters
- punctuation
- stopwords

`we need to remove them inorder to train the model properly`

In [11]:
from nltk.corpus import stopwords
import re

# import nltk
# nltk.download('stopwords')

stop_words = set(stopwords.words('english')) # Creating Stopwords List

def clean_text(tweet):
    text = tweet.lower()
    text = re.sub(r"http\S+", "", text) # Remove URLs
    text = re.sub(r"[^a-zA-Z]", " ", text) # Remove Special Characters and Numbers
    words = text.split() # Split Text into Words (Tokenization)
    words = [word for word in words if word not in stop_words] # Remove Stopwords
    
    return " ".join(words) # Join Words Back Into Sentence

#### Apply Cleaning

In [12]:
ds['clean_text'] = ds['text'].apply(clean_text)
ds.head()

,text,emotion,clean_text
0,im feeling rather rotten so im not very ambiti...,sadness,im feeling rather rotten im ambitious right
1,im updating my blog because i feel shitty,sadness,im updating blog feel shitty
2,i never make her separate from me because i do...,sadness,never make separate ever want feel like ashamed
3,i left with my bouquet of red and yellow tulip...,joy,left bouquet red yellow tulips arm feeling sli...
4,i was feeling a little vain when i did this one,sadness,feeling little vain one

# Text Vectorization (TF-IDF)

- Machine learning models cannot understand text directly.
- So we convert text into numerical vectors.

`NOTE : TF-IDF Stands - Term Frequency-Inverse Document Frequency`

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(ds['clean_text'])
y = ds['emotion']

# Train Test Split

#### We split data into:

- Training Data (80%)
- Testing Data (20%)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)